### ISSUE TITLE
Add already prepared css-styled text to body

### ISSUE THREAD

**Issue by vkeyboardv** [vkeyboardv/homepage#11]
Add already prepared css-styled text to body

**Task list:**
- [x] Add info to ```<body>```
- [x] Change body background (vs code theme style)
- [x] Add other styles for body (eg vs code styled ```::selection```)

New branch name: feature/body
