### ISSUE TITLE
Prepare index.html and directories

### ISSUE THREAD

**Issue by vkeyboardv** [vkeyboardv/homepage#9]
Prepare index.html and directories

**Task list:**
- [x] Create src/css, src/js, src/img directories
- [x] Create src/css/styles.css file
- [x] Set up connect to highlight.js
- [x] Set up VS2015 theme styles
- [x] Create any css-styled text in ```<body>```

Working branch name: feature/add-vs-theme
